Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2023
Var
// Seção de Declarações das variáveis 

numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digito o numero: ")
leia(numero)
escreva("O numero informado foi: ", numero)


Fimalgoritmo